---
title: "1.1 细胞生物学概述"
author: "Yonghe"
date: "8/13/2021"
output:
  html_document: 
    theme: readable
    toc: true
    toc_float: true
    toc_depth: 4
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.1细胞生物学概述

### 一、细胞生物学概述

1.  细胞生物学的概念

    细胞生物学是指，研究细胞生命活动基本规律的科学。从显微、亚显微及分子水平等不同层次研究细胞的组成、结构、功能、细胞重大生命活动以及细胞与细胞间的相互关系。

2.  细胞生物学与医学的关系

    医学细胞生物学是指，以人体细胞为对象，研究其结构、功能、增殖、分化、遗传、变异、衰老、死亡等生命活动与疾病的关系及可能的治疗方法。

    -   基础医学方面：细胞生物学揭示人类疾病的发病机理，例如肿瘤的发生、动脉粥样硬化的发生、糖尿病的发生、G蛋白偶联受体的发现与分析等。

    -   临床医学方面：细胞生物学为人类疾病的临床诊断提供依据，并为药物研发与临床治疗提供依据。例如单克隆抗体、细胞治疗、干细胞与再生医学等。

### 二、细胞生物学的基本内容

1.  细胞的生物膜系统
2.  细胞的遗传信息系统、基因的表达与调控
3.  细胞骨架系统
4.  细胞信号转导与信号网络调控
5.  细胞中DNA
    与蛋白质之间的相互作用，尤其是基因组与非组蛋白之间的相互作用
6.  基因表达产物的逐级装配以及细胞结构系统的组装
7.  细胞重大生命活动，如细胞增殖、细胞分化、细胞衰老、细胞凋亡

### 三、细胞生物学的发展历史

#### 1. 细胞的发现（1665-1838）

-   1665年，英国物理学家罗伯特·胡克首次观察到细胞结构，即软木死细胞的细胞壁，并命名细胞。
-   1674年，荷兰学者列文虎克首次观察到活细胞，如：原生动物、鱼类红细胞。

#### 2. 细胞学说 （1838-1875）

1838年德国植物学家施莱登、1839年德国动物学家施旺、1858年德国病理学家魏尔肖提出并扩展细胞学说，其基本内容是：

-   一切生物都由细胞及细胞产物构成。
-   细胞是生物形态结构和功能活动的基本单位
-   新细胞由老细胞分裂产生

#### 3. 经典细胞学时期 （1875-1900）

1.  原生质理论的提出

```{=html}
<!-- -->
```
    **原生质**是指，细胞内生命物质的基础，是由糖脂、脂质、蛋白质、核酸等多种物质构成的复杂胶体。

    **原生质体**是指，又原生质分化产生的，细胞膜、细胞质与细胞核构成的具有特定结构与功能的系统，即细胞。原生质体不包括细胞壁。

2.  细胞分裂的研究

3.  细胞器的发现

    如：线粒体、叶绿体、内质网、高尔基体、溶酶体、细胞核等。

#### 4. 实验细胞学时期 (1900-1950)

1.  细胞遗传学是指，遗传学与细胞学结合的学科，主要是从细胞的角度，特别是以染色体为对象研究遗传现象，阐释遗传与变异的本质。
2.  细胞生理学是指，生理学与细胞学结合的学科，主要研究细胞的的营养、代谢、能量转换以及细胞对环境变化的反应等内容。
3.  细胞化学是指，研究细胞生命活动中个化学成分的性质、功能与分布规律的学科，通过理化技术对细胞组分进行定性，定量分析，研究其在细胞生命活动中的作用。

#### 四、细胞生物学的发展趋势

1.  当代细胞生物学的主要方向：分子细胞生物学

    分子生物学是指，在分子水平上研究细胞生命活动的基本规律，即将细胞的生命活动视为物质、能量、信息相统一的过程，研究细胞生命活动中，生物大分子、细胞器的行为和规律与相互关系。主要包括以下两个方向：

    1.  基因与基因产物对细胞生命活动对调控

    2.  基因产物与其他生物分子对逐级装配以及细胞结构系统的组装

2.  当代细胞生物学的主要特点

    1.  从细胞的结构和功能 ➡️ 细胞重大生命活动

    2.  从单一的基因与蛋白质 ➡️
        基因组与蛋白质组以及生物大分子之间的相互作用

    3.  从细胞信号转导途径 细胞信号调控网络

    4.  从体外、静态研究 体内、动态活细胞研究

    5.  从分子治疗 细胞治疗

3.  当代细胞生物学的主要问题

    1.  基因组如何在时间和空间上有序表达

    2.  基因表达的产物如何逐级装配形成细胞结构

    3.  基因表达的产物如何调节细胞的生命活动

4.  我国生命科学基础规划

    分子生物学、细胞生物学、神经生物学、生态学

5.  美国国立卫生研究院对生命科学发展的预测

    1.  三大疾病

        癌症

        心血管疾病

        传染性疾病：艾滋病、肝炎

    2.  五大方向

        细胞周期调控

        细胞衰老

        细胞凋亡

        细胞信号转导

        DNA的损伤与修复
