---
title: "1.2-细胞的基本特征"
author: "Yonghe"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: readable
    toc: true
    toc_float: true
    toc_depth: 5
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.2 细胞的基本特征

### 一、细胞是生命活动的基本单位

1.  一切生物均由细胞构成,细胞是构成生命体结构的基本单位(除病毒)。
2.  细胞有独立、自控、稳定的代谢系统,是生命体代谢的基本单位。
3.  细胞是生命体生长、发育、繁殖的基本单位。
4.  细胞具有完整的遗传信息及其表达与调控系统,是生命体遗传的基本单位。
5.  细胞是生命起源的归宿与生命演化的起点。
6.  生命活动依赖细胞的完整性,细胞是生命活动的基本单位。

### 二、细胞的共性

1.  所有细胞都拥有相似的化学组成。

2.  所有细胞都拥有以脂质-蛋白质为基础的生物膜系统。

3.  所有细胞都拥有以核酸-蛋白质为基础的遗传系统。

4.  所有细胞都通过核糖体合成蛋白质。

5.  所有细胞都通过分裂的方式增殖。

### 三、细胞的基本特征

#### 1. 细胞的大小

1.  细胞体积守恒规律

    -   生物体组织、器官的大小主要取决于细胞的数量,与单个细胞的尺寸大小无关。

    -   不同物种间细胞的尺寸有差异,但不同物种间相似组织、器官中细胞的尺寸相似。

2.  细胞平均直径约为10\~100m。

    -   目前已知最小的细胞是支原体.直径约01\~03um

    -   目前已知最大的细胞是鸵鸟卵细胞,直径约5cm。

3.  细胞的尺寸极限

    1.  细胞尺寸上限

        -   细胞的体积与比表面积成反比,为了更好的与环境进行物质、能量与信息交流,绝大多数细胞需要一定的比表面积,因此细胞尺寸有上限。

        -   细胞核的大小差异不大,所能调控的范围有限,故细胞尺寸有上限。为了缓解核质冲突,有些生物的细胞存在多核现象。

        -   细胞内某些重要分子的存量很少,当细胞体积增大时,这些分子的浓度下降。而生化反应需要一定的分子浓度才能进行,故细胞尺寸有上限。

    2.  细胞尺寸下限

        -   由于核糖体是所有细胞的共性,故细胞尺寸绝不能小于核糖体,核糖体直径约25nm。一般认为细胞尺寸的下限不能小于100m。

#### 2. 细胞的组装

    1.  细胞组装的类型

        1.  **模板组装**是指,由模板介导,在酶的催化下合成新的与模板相同的分子。如:DNA、RNA的合成。

        2.  **酶促组装**是指,相同的单体在不同酶的作用下形成不同的产物。如:以葡萄糖为原料,在不同的酶系催化下,既可合成纤维素,也可合成淀粉。

        3.  **自组装**是指,无需酶或模板介导,组装信息蕴藏于单体本身,由单体自发组装形成有序结构。依据是否需要分子伴侣的协助,自组装可分为**直接组装**与**协助组装**。

            -   **直接组装**无需分子伴侣协助,如:微管、微丝的组装。

            -   **协助组装**需要分子伴侣协助,如:核质蛋白能够促进组蛋白与DNA的相互作用,从而协助核小体组装。

    2.  细胞组装的意义

        1.  减少细胞生命活动所需的遗传信息量。
        2.  减少与修正蛋白质合成过程中的错误。
        3.  通过组装与去组装调控细胞生命活动.

#### 3. 细胞的结构与功能的关系

    1.  红细胞

        -   哺乳动物红细胞的结构为:形状呈两面凹陷的圆饼状,体积小,无多余细胞器,其基本结构为细胞质膜包被血红蛋白。

        -   哺乳动物红细胞的功能为:在体内运载O2,并进行O2与CO2的交换。

        -   红细胞的形状有利于在血管内快速运输;体积小,比表面积大,有利于提高气体交换率;主要组成部分为血红蛋白,有利于气体结合。

    2.  精、卵细胞

        哺乳动物精子细胞呈蝌蚪状,其主要功能为为子代提供父方的基因组。精子细长的尾部使之具有运动能

        力以寻找卵细胞,除线粒体供能外无其他细胞器,头部含有父方基因组并可以分泌溶解细胞质膜的酶,有利

        于进入卵细胞。

        哺乳动物卵子细胞呈球形,其主要功能为为子代提供母方的基因组,并为受精卵早期发育提供必须的营

        养。故卵子细胞体积较大,内部除基因组外还含有大量mRNA和蛋白质,球形的表面则适合于精子细胞结合。

    3.  分泌细胞

        分泌细胞具有极性,一端行使吸收功能,为吸收表面;一端行使分泌功能,为分泌表面。吸收表面的质

        膜形成大量褶皱,褶皱内侧排列有大量线粒体,有助于促进物质的跨膜运输。分泌表面的质膜形成大量微绒

        毛,增加细胞表面积,促进分泌。

    4.  保卫细胞

        保卫细胞是高度特化的薄壁细胞,依据形状可将其分为两类,即肾脏形保卫细胞与哑铃形保卫细胞。除

        禾本科、莎草科、灯心草科的植物外,绝大多数种类植物的气孔由肾脏形保卫细胞构成(如图1.2.2A);而

        常见的禾本科作物如水稻等则由哑铃形保卫细胞构成。

        保卫细胞对环境变化极为敏感,能够通过自身的体积变化控制气孔的张开与关闭。对于

        肾脏形保卫细胞而言,其内侧(靠近孔隙侧)的细胞壁较厚,外侧的细胞壁较薄。当保卫细胞吸水膨胀时,

        外侧细胞壁向外弯曲,拉动内侧细胞壁,从而张开气孔。对于哑铃形保卫细胞而言,位于两端的球形部分细

        胞壁较薄,而位于中部的细长部分细胞壁较厚。当保卫细胞吸水时,两端球形部分膨胀,使位于中部的细长

        部分分开,从而张开气孔。反之,保卫细胞失水时,则气孔关闭。
